workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      node: 20.20.0
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Prebuild Expo
        script: npx expo prebuild --clean
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/**/**/*.apk
